### ISSUE TITLE
Unirest throws exception

### ISSUE THREAD

**Issue by djken2006** [deeplearning4j/gym-java-client#5] opened 2016-12-31 13:50 UTC
GymEnv<Box, Integer, DiscreteSpace> mdp = new GymEnv<Box, Integer, DiscreteSpace>                 ("CartPole-v0", false, false);

		for (;;) {
			mdp.reset();
			while (!mdp.isDone()) {
				mdp.step(0);
			}
		}

Run the above code and after some minutes the following exception will be thrown:

I/O exception (java.net.BindException) caught when processing request to {}->http://127.0.0.1:5000: Address already in use: connect
org.apache.http.impl.execchain.RetryExec execute
Retrying request to {}->http://127.0.0.1:5000
Exception in thread "main" java.lang.NullPointerException
	at org.deeplearning4j.gym.ClientUtils.unirestCrash(ClientUtils.java:57)
	at org.deeplearning4j.gym.ClientUtils.post(ClientUtils.java:26)
	at org.deeplearning4j.gym.Client.reset(Client.java:103)
	at org.deeplearning4j.rl4j.mdp.gym.GymEnv.reset(GymEnv.java:67)
	at Cartpole.main(Cartpole.java:13)

**Comment by saudet** [comment] 2017-07-30 01:53
Duplicate of deeplearning4j/rl4j#19 and #13 

Please post this over there not here: https://github.com/openai/gym-http-api/issues

If Jython is good enough to call OpenAI Gym, I'd like to use that, so please try it out if you can! Thanks

**Closed by saudet** 2017-07-30 01:53 UTC
Labels: duplicate
