### ISSUE TITLE
"RuntimeException: Connection error" on client.step

### ISSUE THREAD

**Issue by neph1** [deeplearning4j/gym-java-client#13] opened 2017-05-28 09:05 UTC
#### Issue Description
This crash happens eventually in every CartPole-v0 simulation I run, if I let it run long enough. It can happen before, but seems to _always_ happen as the total reward nears 30000. (The total reward at the last step before the crash is usually above 29200)
I've tried using Thread.sleep to avoid it (in case it was some overflow issue), but to no avail.

Stacktrace:
Exception in thread "main" java.lang.RuntimeException: Connection error
        at org.deeplearning4j.gym.ClientUtils.unirestCrash(ClientUtils.java:60)
	at org.deeplearning4j.gym.ClientUtils.post(ClientUtils.java:26)
	at org.deeplearning4j.gym.Client.step(Client.java:87)

#### Version Information

dl4j 0.8.0 and gym-java-client 0.8.0
Unirest is version 1.4.9
I run the server and client on Linux(OpenSuse) x64 with Python3.

**Comment by neph1** [comment] 2017-06-04 19:15
Update but unfortunately no solution to this.
I managed to get past the 29xxx problem by adding a Thread.sleep(20000) to each episode above 29000. Now it seems to go on indefinitely, but this is of course not acceptable. I've tried lower sleeps, pr just pausing once but it still crashed sometimes. Maybe someone else has some input on this.

**Comment by saudet** [comment] 2017-06-05 00:23
Does this happen with any of the examples at https://github.com/deeplearning4j/dl4j-examples/tree/master/rl4j-examples?

**Comment by ecthx** [comment] 2017-07-30 01:30
I'm getting same crash in the examples and current rl4j master:

From examples:
`java.lang.RuntimeException: Connection error
	at org.deeplearning4j.gym.ClientUtils.unirestCrash(ClientUtils.java:60)
	at org.deeplearning4j.gym.ClientUtils.post(ClientUtils.java:26)
	at org.deeplearning4j.gym.Client.reset(Client.java:103)
	at org.deeplearning4j.rl4j.mdp.gym.GymEnv.reset(GymEnv.java:67)
	at org.deeplearning4j.rl4j.learning.Learning.initMdp(Learning.java:67)
	at org.deeplearning4j.rl4j.learning.async.AsyncThread.run(AsyncThread.java:73)
`

This is from rl4j master:

`java.lang.RuntimeException: Connection error
	at org.deeplearning4j.gym.ClientUtils.unirestCrash(ClientUtils.java:55)
	at org.deeplearning4j.gym.ClientUtils.post(ClientUtils.java:23)
	at org.deeplearning4j.gym.Client.step(Client.java:85)
	at org.deeplearning4j.rl4j.mdp.gym.GymEnv.step(GymEnv.java:56)
	at org.deeplearning4j.rl4j.learning.async.AsyncThreadDiscrete.trainSubEpoch(AsyncThreadDiscrete.java:80)
	at org.deeplearning4j.rl4j.learning.async.AsyncThread.run(AsyncThread.java:82)
Caused by: com.mashape.unirest.http.exceptions.UnirestException: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:5000 [/127.0.0.1] failed: Cannot assign requested address (connect failed)
	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143)
	at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:68)
	at org.deeplearning4j.gym.ClientUtils.post(ClientUtils.java:21)
	... 4 more
`

**Comment by saudet** [comment] 2017-07-30 01:51
Duplicate of https://github.com/deeplearning4j/rl4j/issues/19

Please post this over there not here: https://github.com/openai/gym-http-api/issues

If Jython is good enough to call OpenAI Gym, I'd like to use that, so please try it out if you can! Thanks

**Closed** 2017-07-30 01:52 UTC
Labels: duplicate
